
DROP TABLE IF EXISTS  INFAIN.INTERVENTION ;
DROP TABLE IF EXISTS  INFAIN.INTERVENTION_BIS ;
DROP TABLE IF EXISTS  INFAIN.DOSSIER ;
DROP TABLE IF EXISTS  INFAIN.SALARIE ;
DROP TABLE IF EXISTS  INFAIN.VEHICULE ;

DROP VIEW IF EXISTS INFAIN.vKilometrage ;

DROP SCHEMA IF EXISTS INFAIN;