ALTER TABLE
  SOFTWARE.REF_LIB_DEVELOPPEUR
ALTER COLUMN
  ID_DEVELOPPEUR
    INT NOT NULL;
	GO
ALTER TABLE SOFTWARE.REF_LIB_DEVELOPPEUR ADD PRIMARY KEY (ID_DEVELOPPEUR)
GO

ALTER TABLE
  SOFTWARE.DEVELOPPEUR
ALTER COLUMN
  ID_DEVELOPPEUR
    INT NOT NULL;
	GO
ALTER TABLE SOFTWARE.DEVELOPPEUR ADD PRIMARY KEY (ID_DEVELOPPEUR)
GO
ALTER TABLE SOFTWARE.DEVELOPPEUR
ADD CONSTRAINT FK_ID_DEVELOPPEUR FOREIGN KEY (ID_DEVELOPPEUR)
    REFERENCES SOFTWARE.REF_LIB_DEVELOPPEUR (ID_DEVELOPPEUR) ;
GO

ALTER TABLE
  SOFTWARE.REF_LIB_EDITEUR
ALTER COLUMN
  ID_EDITEUR
    INT NOT NULL;
	GO
	ALTER TABLE SOFTWARE.REF_LIB_EDITEUR ADD PRIMARY KEY (ID_EDITEUR)
	GO
	ALTER TABLE SOFTWARE.DEVELOPPEUR
ADD CONSTRAINT FK_ID_EDITEUR FOREIGN KEY (ID_EDITEUR)
    REFERENCES SOFTWARE.REF_LIB_EDITEUR (ID_EDITEUR) ;
GO

ALTER TABLE
  SOFTWARE.REF_LIB_PAYS
ALTER COLUMN
  ID_PAYS
    INT NOT NULL;
	GO
		ALTER TABLE SOFTWARE.REF_LIB_PAYS ADD PRIMARY KEY (ID_PAYS)
		GO

		ALTER TABLE SOFTWARE.DEVELOPPEUR
ADD CONSTRAINT FK_ID_PAYS FOREIGN KEY (ID_PAYS)
    REFERENCES SOFTWARE.REF_LIB_PAYS (ID_PAYS) ;
GO

ALTER TABLE
  SOFTWARE.REF_LIB_JEUX
ALTER COLUMN
  ID_JEU
    INT NOT NULL;
	GO
		ALTER TABLE SOFTWARE.REF_LIB_JEUX ADD PRIMARY KEY (ID_JEU)
GO
		ALTER TABLE
  SOFTWARE.JEUX
ALTER COLUMN
  ID_JEU
    INT NOT NULL;
	GO
		ALTER TABLE SOFTWARE.JEUX ADD PRIMARY KEY (ID_JEU)
		GO
		ALTER TABLE SOFTWARE.JEUX
ADD CONSTRAINT FK_ID_DEV_JEUX FOREIGN KEY (ID_DEVELOPPEUR)
    REFERENCES SOFTWARE.REF_LIB_DEVELOPPEUR (ID_DEVELOPPEUR) ;
GO

ALTER TABLE SOFTWARE.JEUX
ADD CONSTRAINT FK_ID_JEU_JEUX FOREIGN KEY (ID_JEU)
    REFERENCES SOFTWARE.REF_LIB_JEUX (ID_JEU) ;
GO

ALTER TABLE
  SOFTWARE.REF_LIB_REGION
ALTER COLUMN
  ID_REGION
    INT NOT NULL;
	GO

		ALTER TABLE SOFTWARE.REF_LIB_REGION ADD PRIMARY KEY (ID_REGION)

		GO
		
		ALTER TABLE
  SOFTWARE.PAYS
ALTER COLUMN
  ID_PAYS
    INT NOT NULL;
	GO
			ALTER TABLE SOFTWARE.PAYS ADD PRIMARY KEY (ID_PAYS)

			GO
			ALTER TABLE SOFTWARE.PAYS
ADD CONSTRAINT FK_ID_PAYS_PAYS FOREIGN KEY (ID_PAYS)
    REFERENCES SOFTWARE.REF_LIB_PAYS (ID_PAYS) ;
GO
ALTER TABLE SOFTWARE.PAYS
ADD CONSTRAINT FK_ID_REGION_PAYS FOREIGN KEY (ID_REGION)
    REFERENCES SOFTWARE.REF_LIB_REGION (ID_REGION) ;
GO