CREATE VIEW SOFTWARE.SYNTHESE AS
SELECT J.*, D.DATE_CREATION, D.ID_EDITEUR,D.ID_PAYS, D.NB_EMPLOYES,
P.ID_REGION, P.NB_JOUEUR_PAYS, RJ.CODE_JEU, RJ.LIB_JEU,
RD.CODE_DEVELOPPEUR, RD.LIB_DEVELOPPEUR,
RE.CODE_EDITEUR, RE.LIB_EDITEUR,
RP.CODE_PAYS, RP.LIB_PAYS, RR.CODE_REGION, RR.LIB_REGION
FROM SOFTWARE.JEUX J
INNER JOIN SOFTWARE.DEVELOPPEUR D
ON J.ID_DEVELOPPEUR = D.ID_DEVELOPPEUR
INNER JOIN SOFTWARE.PAYS P
ON D.ID_PAYS = P.ID_PAYS
INNER JOIN SOFTWARE.REF_LIB_JEUX RJ 
ON J.ID_JEU = RJ.ID_JEU
INNER JOIN SOFTWARE.REF_LIB_DEVELOPPEUR RD
ON D.ID_DEVELOPPEUR = RD.ID_DEVELOPPEUR
INNER JOIN SOFTWARE.REF_LIB_EDITEUR RE
ON D.ID_EDITEUR = RE.ID_EDITEUR
INNER JOIN SOFTWARE.REF_LIB_PAYS RP
ON P.ID_PAYS = RP.ID_PAYS
INNER JOIN SOFTWARE.REF_LIB_REGION RR
ON P.ID_REGION = RR.ID_REGION
