SELECT
EN.NOM_EMPLOYE, SR.NB_EMPLOYES_GERES
FROM VIDEOLOC.EMPLOYE EN
INNER JOIN
(
SELECT COUNT(*) AS NB_EMPLOYES_GERES, M.FK_CLEF_GERANT
FROM VIDEOLOC.EMPLOYE E
INNER JOIN VIDEOLOC.MAGASIN M
ON E.FK_CLEF_MAGASIN = M.CLEF_AGENCE
WHERE E.CLEF_EMPLOYE != M.FK_CLEF_GERANT
GROUP BY M.FK_CLEF_GERANT
) SR
ON SR.FK_CLEF_GERANT = EN.CLEF_EMPLOYE