IF NOT EXISTS ( SELECT  *
                FROM    sys.schemas
                WHERE   name = N'VIDEOLOC' )
    EXEC('CREATE SCHEMA [VIDEOLOC]');
GO


CREATE TABLE VIDEOLOC.MAGASIN
(		
   CLEF_AGENCE INT IDENTITY(1,1) PRIMARY KEY,
   FK_CLEF_GERANT INT ,
   VILLE VARCHAR(60)
);

INSERT INTO VIDEOLOC.MAGASIN  VALUES (2,'Paris');
INSERT INTO VIDEOLOC.MAGASIN  VALUES (5,'Lyon');


CREATE TABLE VIDEOLOC.EMPLOYE
(		
   CLEF_EMPLOYE INT IDENTITY(1,1) PRIMARY KEY,
   FK_CLEF_MAGASIN INT ,
   FK_CLEF_POSTE INT ,
   NOM_EMPLOYE VARCHAR(60),
   PRENOM_EMPLOYE VARCHAR(60),
   SALAIRE FLOAT
);

INSERT INTO VIDEOLOC.EMPLOYE  VALUES (1,3,'HADDAD', 'George',50000);
INSERT INTO VIDEOLOC.EMPLOYE  VALUES (1,1,'CHEVALIER', 'Monique',60000);
INSERT INTO VIDEOLOC.EMPLOYE  VALUES (1,2,'BECENBOIS','Paul', 35000);
INSERT INTO VIDEOLOC.EMPLOYE  VALUES (2,3,'DELPECH','Francoise', 45000);
INSERT INTO VIDEOLOC.EMPLOYE  VALUES (2,1,'LIN','Caroline', 55000);


CREATE TABLE VIDEOLOC.POSTE
(		
   CLEF_POSTE INT IDENTITY(1,1) PRIMARY KEY,
   NOM_POSTE VARCHAR(60)
   )

INSERT INTO VIDEOLOC.POSTE VALUES ('Gérant') ;
INSERT INTO VIDEOLOC.POSTE VALUES ('Manutentionnaire') ;
INSERT INTO VIDEOLOC.POSTE VALUES ('Vendeur') ;


ALTER TABLE VIDEOLOC.MAGASIN
ADD CONSTRAINT FK_GERANT FOREIGN KEY(FK_CLEF_GERANT) REFERENCES VIDEOLOC.EMPLOYE(CLEF_EMPLOYE);

ALTER TABLE VIDEOLOC.EMPLOYE
ADD CONSTRAINT FK_EMPLOYE FOREIGN KEY(FK_CLEF_MAGASIN) REFERENCES VIDEOLOC.MAGASIN(CLEF_AGENCE);

ALTER TABLE VIDEOLOC.EMPLOYE
ADD CONSTRAINT FK_POSTE FOREIGN KEY(FK_CLEF_POSTE) REFERENCES VIDEOLOC.POSTE(CLEF_POSTE);

INSERT INTO VIDEOLOC.EMPLOYE  VALUES (2,2,'Robert','Sylvain', 18000);
INSERT INTO VIDEOLOC.MAGASIN  VALUES (5,'Grenoble');
INSERT INTO VIDEOLOC.EMPLOYE  VALUES (3,3,'Dupond','Thierry', 30000);
INSERT INTO VIDEOLOC.EMPLOYE  VALUES (3,1,'Durand','Mélanie', 50000);

UPDATE VIDEOLOC.MAGASIN
SET FK_CLEF_GERANT = 8
WHERE CLEF_AGENCE = 3

INSERT INTO VIDEOLOC.POSTE VALUES ('Marketing') ;
INSERT INTO VIDEOLOC.POSTE VALUES ('Data Scientist') ;