SELECT F.TITRE_FILM
FROM VIDEOLOC.FILM F
INNER JOIN
(SELECT COUNT(*) AS NB,
AF.FK_CLEF_FILM
FROM VIDEOLOC.ACTEUR_FILM AF
GROUP BY AF.FK_CLEF_FILM
HAVING COUNT(*) = 1
) SR
ON F.CLEF_FILM = SR.FK_CLEF_FILM