CREATE SCHEMA VIDEOLOC
GO

CREATE TABLE VIDEOLOC.REALISATEUR
(		
   CLEF_REALISATEUR INT IDENTITY(1,1) PRIMARY KEY,
   NOM_REALISATEUR VARCHAR(60)
);

INSERT INTO VIDEOLOC.REALISATEUR  VALUES ('EASTWOOD');
INSERT INTO VIDEOLOC.REALISATEUR  VALUES ('LYNCH');
INSERT INTO VIDEOLOC.REALISATEUR  VALUES ('COPPOLA');


CREATE TABLE VIDEOLOC.FILM (
CLEF_FILM INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
FK_CLEF_REALISATEUR INT NOT NULL,
NUMERO_CATALOGUE VARCHAR(50) NOT NULL,
CATEGORIE VARCHAR(50) NOT NULL CHECK (CATEGORIE IN('Action', 'Famille', 'Drame', 'Comédie', 'Horreur', 'Fantastique', 'Science-fiction', 'Adulte')),
TITRE_FILM VARCHAR(50) 
CONSTRAINT FK_REAL FOREIGN KEY (FK_CLEF_REALISATEUR)
REFERENCES VIDEOLOC.REALISATEUR(CLEF_REALISATEUR)
 );

INSERT INTO VIDEOLOC.FILM  VALUES (3,'002032501','Action','Apocalypse Now');
INSERT INTO VIDEOLOC.FILM  VALUES (3,'002032502','Action','The conversation');
INSERT INTO VIDEOLOC.FILM  VALUES (2,'002032503','Fantastique','Twin Peaks saison 1');
INSERT INTO VIDEOLOC.FILM  VALUES (2,'002064518','Fantastique','Twin Peaks saison 2');
INSERT INTO VIDEOLOC.FILM  VALUES (2,'002066238','Fantastique','Twin Peaks saison 3');
INSERT INTO VIDEOLOC.FILM  VALUES (1,'003866239','Drame','Million dollar baby');
INSERT INTO VIDEOLOC.FILM  VALUES (1,'003866321','Action','Impitoyable');


CREATE TABLE VIDEOLOC.ACTEUR 
(		
   CLEF_ACTEUR INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
   NOM_ACTEUR VARCHAR(60)
);

INSERT INTO VIDEOLOC.ACTEUR  VALUES ('EASTWOOD');
INSERT INTO VIDEOLOC.ACTEUR  VALUES ('BRANDO');
INSERT INTO VIDEOLOC.ACTEUR  VALUES ('DUVALL');
INSERT INTO VIDEOLOC.ACTEUR  VALUES ('SHEEN');
INSERT INTO VIDEOLOC.ACTEUR  VALUES ('HACKMAN');
INSERT INTO VIDEOLOC.ACTEUR  VALUES ('LYNCH');
INSERT INTO VIDEOLOC.ACTEUR  VALUES ('MACLACHLAN');
INSERT INTO VIDEOLOC.ACTEUR  VALUES ('SWANK');
INSERT INTO VIDEOLOC.ACTEUR  VALUES ('FREEMAN');

CREATE TABLE VIDEOLOC.ACTEUR_FILM
(
	CLEF_ACTEUR_FILM INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	
	FK_CLEF_ACTEUR INT NOT NULL,
	FK_CLEF_FILM INT NOT NULL,
	CONSTRAINT FK_ACTEUR FOREIGN KEY (FK_CLEF_ACTEUR)
REFERENCES VIDEOLOC.ACTEUR(CLEF_ACTEUR),
CONSTRAINT FK_FILM FOREIGN KEY (FK_CLEF_FILM)
REFERENCES VIDEOLOC.FILM(CLEF_FILM)
);

INSERT INTO VIDEOLOC.ACTEUR_FILM  VALUES (2,1);
INSERT INTO VIDEOLOC.ACTEUR_FILM  VALUES (3,1);
INSERT INTO VIDEOLOC.ACTEUR_FILM  VALUES (4,1);
INSERT INTO VIDEOLOC.ACTEUR_FILM  VALUES (5,2);
INSERT INTO VIDEOLOC.ACTEUR_FILM  VALUES (4,1);
INSERT INTO VIDEOLOC.ACTEUR_FILM  VALUES (5,2);
INSERT INTO VIDEOLOC.ACTEUR_FILM  VALUES (6,3);
INSERT INTO VIDEOLOC.ACTEUR_FILM  VALUES (7,3);
INSERT INTO VIDEOLOC.ACTEUR_FILM  VALUES (6,4);
INSERT INTO VIDEOLOC.ACTEUR_FILM  VALUES (7,4);
INSERT INTO VIDEOLOC.ACTEUR_FILM  VALUES (6,5);
INSERT INTO VIDEOLOC.ACTEUR_FILM  VALUES (7,5);
INSERT INTO VIDEOLOC.ACTEUR_FILM  VALUES (1,6);
INSERT INTO VIDEOLOC.ACTEUR_FILM  VALUES (9,6);




