CREATE SCHEMA VIDEOLOC
GO

CREATE TABLE VIDEOLOC.REALISATEUR
(		
   CLEF_REALISATEUR INT IDENTITY(1,1) PRIMARY KEY,
   NOM_REALISATEUR VARCHAR(60)
);

INSERT INTO VIDEOLOC.REALISATEUR  VALUES ('EASTWOOD');
INSERT INTO VIDEOLOC.REALISATEUR  VALUES ('LYNCH');
INSERT INTO VIDEOLOC.REALISATEUR  VALUES ('COPPOLA');


CREATE TABLE VIDEOLOC.FILM (
CLEF_FILM INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
NUMERO_CATALOGUE VARCHAR(50) NOT NULL,
CATEGORIE VARCHAR(50) NOT NULL CHECK (CATEGORIE IN('Action', 'Famille', 'Drame', 'Comédie', 'Horreur', 'Fantastique', 'Science-fiction', 'Adulte')),
TITRE_FILM VARCHAR(50) 
 );

INSERT INTO VIDEOLOC.FILM  VALUES ('002032501','Action','Apocalypse Now');
INSERT INTO VIDEOLOC.FILM  VALUES ('002032502','Action','The conversation');
INSERT INTO VIDEOLOC.FILM  VALUES ('002032503','Fantastique','Twin Peaks saison 1');
INSERT INTO VIDEOLOC.FILM  VALUES ('002064518','Fantastique','Twin Peaks saison 2');
INSERT INTO VIDEOLOC.FILM  VALUES ('002066238','Fantastique','Twin Peaks saison 3');
INSERT INTO VIDEOLOC.FILM  VALUES ('003866239','Drame','Million dollar baby');
INSERT INTO VIDEOLOC.FILM  VALUES ('003866321','Action','Impitoyable');


CREATE TABLE VIDEOLOC.ACTEUR 
(		
   CLEF_ACTEUR INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
   NOM_ACTEUR VARCHAR(60)
);

INSERT INTO VIDEOLOC.ACTEUR  VALUES ('EASTWOOD');
INSERT INTO VIDEOLOC.ACTEUR  VALUES ('BRANDO');
INSERT INTO VIDEOLOC.ACTEUR  VALUES ('DUVALL');
INSERT INTO VIDEOLOC.ACTEUR  VALUES ('SHEEN');
INSERT INTO VIDEOLOC.ACTEUR  VALUES ('HACKMAN');
INSERT INTO VIDEOLOC.ACTEUR  VALUES ('LYNCH');
INSERT INTO VIDEOLOC.ACTEUR  VALUES ('MACLACHLAN');
INSERT INTO VIDEOLOC.ACTEUR  VALUES ('SWANK');
INSERT INTO VIDEOLOC.ACTEUR  VALUES ('FREEMAN');





