IF NOT EXISTS ( SELECT  *
                FROM    sys.schemas
                WHERE   name = N'VIDEOLOC' )
    EXEC('CREATE SCHEMA [VIDEOLOC]');
GO


CREATE TABLE VIDEOLOC.MAGASIN
(		
   CLEF_AGENCE INT IDENTITY(1,1) PRIMARY KEY,
   VILLE VARCHAR(60)
);

INSERT INTO VIDEOLOC.MAGASIN  VALUES ('Paris');
INSERT INTO VIDEOLOC.MAGASIN  VALUES ('Lyon');


CREATE TABLE VIDEOLOC.EMPLOYE
(		
   CLEF_EMPLOYE INT IDENTITY(1,1) PRIMARY KEY,
   NOM_EMPLOYE VARCHAR(60),
   PRENOM_EMPLOYE VARCHAR(60),
   SALAIRE FLOAT
);

INSERT INTO VIDEOLOC.EMPLOYE  VALUES ('HADDAD', 'George',50000);
INSERT INTO VIDEOLOC.EMPLOYE  VALUES ('CHEVALIER', 'Monique',60000);
INSERT INTO VIDEOLOC.EMPLOYE  VALUES ('BECENBOIS','Paul', 35000);
INSERT INTO VIDEOLOC.EMPLOYE  VALUES ('DELPECH','Francoise', 45000);
INSERT INTO VIDEOLOC.EMPLOYE  VALUES ('LIN','Caroline', 55000);


CREATE TABLE VIDEOLOC.POSTE
(		
   CLEF_POSTE INT IDENTITY(1,1) PRIMARY KEY,
   NOM_POSTE VARCHAR(60)
   )

INSERT INTO VIDEOLOC.POSTE VALUES ('Gérant') ;
INSERT INTO VIDEOLOC.POSTE VALUES ('Manutentionnaire') ;
INSERT INTO VIDEOLOC.POSTE VALUES ('Vendeur') ;
