
DROP TABLE IF EXISTS  VIDEOLOC.ACTEUR_FILM ;

DROP TABLE IF EXISTS  VIDEOLOC.FILM ;
DROP TABLE IF EXISTS  VIDEOLOC.ACTEUR  ;
DROP TABLE IF EXISTS  VIDEOLOC.REALISATEUR ;


ALTER TABLE VIDEOLOC.MAGASIN 
DROP CONSTRAINT FK_EMPL  ;

DROP TABLE IF EXISTS  VIDEOLOC.EMPLOYE ;

DROP TABLE IF EXISTS  VIDEOLOC.POSTE ;


DROP TABLE IF EXISTS  VIDEOLOC.MAGASIN ;


DROP SCHEMA IF EXISTS VIDEOLOC;