SELECT
C.NOM_CANDIDAT, C.PRENOM_CANDIDAT
FROM CANDIDATURE.CANDIDAT C 
INNER JOIN CANDIDATURE.DIPLOME_CANDIDAT DC
ON C.CLEF_CANDIDAT = DC.CLEF_CANDIDAT
INNER JOIN CANDIDATURE.DIPLOME D 
ON D.CLEF_DIPLOME = DC.CLEF_DIPLOME
WHERE D.NOM_DIPLOME = 'DEA Economie Ressources Humaines'