DROP TABLE IF EXISTS CANDIDATURE.CANDIDAT_POSTE ;
DROP TABLE IF EXISTS CANDIDATURE.CANDIDAT_LANGUE ;
DROP TABLE IF EXISTS  CANDIDATURE.DIPLOME_CANDIDAT ;


DROP TABLE IF EXISTS  CANDIDATURE.POSTE ;
DROP TABLE IF EXISTS  CANDIDATURE.LANGUE ;

DROP TABLE IF EXISTS  CANDIDATURE.PERIODE_EMPLOI ;
DROP TABLE IF EXISTS  CANDIDATURE.EMPLOYEUR ;
DROP TABLE IF EXISTS  CANDIDATURE.DIPLOME ;
DROP TABLE IF EXISTS  CANDIDATURE.CANDIDAT ;
DROP SCHEMA IF EXISTS CANDIDATURE;
