CREATE SCHEMA CANDIDATURE;
GO

-- Question 1 à traiter, et peut être 3 ?

CREATE TABLE CANDIDATURE.EMPLOYEUR
(		
   ID_EMPLOYEUR  INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
   RAISON_SOCIALE VARCHAR(60)
);

INSERT INTO CANDIDATURE.EMPLOYEUR  VALUES ('SAS');
INSERT INTO CANDIDATURE.EMPLOYEUR  VALUES ('SUADEO');
INSERT INTO CANDIDATURE.EMPLOYEUR  VALUES ('Education Nationale');

/*
ALTER TABLE CANDIDATURE.EMPLOYEUR 
ADD CONSTRAINT PK_EMPLOYEUR PRIMARY KEY (ID_EMPLOYEUR);
*/


-- Question 5 à traiter, peut être 6 ???


CREATE TABLE CANDIDATURE.CANDIDAT (
CLEF_CANDIDAT INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
NUMERO_CANDIDAT VARCHAR(50) NOT NULL,
NOM_CANDIDAT VARCHAR(50) NOT NULL ,
PRENOM_CANDIDAT VARCHAR(50) ,
NUMERO_TELEPHONE VARCHAR(14),
DATE_NAISSANCE DATE
 );

INSERT INTO CANDIDATURE.CANDIDAT  VALUES ('NUM_CAN_20180923_001','ROBERT','Timothee','06-23-79-54-28','1989-06-12');
INSERT INTO CANDIDATURE.CANDIDAT  VALUES ('NUM_CAN_20180923_002','DUPOND','Noemie','06-87-79-27-28','1977-04-12');
INSERT INTO CANDIDATURE.CANDIDAT  VALUES ('NUM_CAN_20180923_003','GAUTHIER','Mafalda','06-65-79-27-28','1974-03-22');


-- Question 2 à traiter, peut être 3 et 6 ???

CREATE TABLE CANDIDATURE.PERIODE_EMPLOI
(		
   ID_PERIODE INT PRIMARY KEY,
   ID_EMPLOYEUR INT not null FOREIGN KEY REFERENCES CANDIDATURE.EMPLOYEUR(ID_EMPLOYEUR),
   DATE_EMBAUCHE DATE,
   DATE_DEPART DATE
);

INSERT INTO CANDIDATURE.PERIODE_EMPLOI  VALUES (1,'1998-01-01','2001-02-01'); 
INSERT INTO CANDIDATURE.PERIODE_EMPLOI  VALUES (1,'2002-01-01','2003-12-31');
INSERT INTO CANDIDATURE.PERIODE_EMPLOI  VALUES (2,'2004-01-01','2014-06-30');
INSERT INTO CANDIDATURE.PERIODE_EMPLOI  VALUES (3,'2015-09-01',NULL);

-- Question7 à traiter


CREATE TABLE CANDIDATURE.POSTE (
CLEF_POSTE INT IDENTITY(1,1),
NUM_AFFICHAGE VARCHAR(50) NOT NULL,
NOM_POSTE VARCHAR(60) ) ;

INSERT INTO CANDIDATURE.POSTE VALUES ('POSTE_201909_IT_CDP_001','Chef de projet Big Data');
INSERT INTO CANDIDATURE.POSTE VALUES ('POSTE_201909_IT_AMOA_001','AMOA Refonte processus comptables');
INSERT INTO CANDIDATURE.POSTE VALUES ('POSTE_201909_IT_DEVFE_001','Developpeur Front End Angular Web vitrine');
INSERT INTO CANDIDATURE.POSTE VALUES ('POSTE_201909_IT_MKT_001','Chef de produit Mobilité Nvx Usages');
INSERT INTO CANDIDATURE.POSTE VALUES ('POSTE_201909_IT_DEVFE_002','Developpeur Front End Vue JS QCM');
INSERT INTO CANDIDATURE.POSTE VALUES ('POSTE_201909_IT_DEVFE_003','Developpeur mobile Android QCM');


-- Question 8 ici ???


-- Question 9


CREATE TABLE CANDIDATURE.DIPLOME (
CLEF_DIPLOME INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
NOM_DIPLOME VARCHAR(50) NOT NULL) ;

INSERT INTO CANDIDATURE.DIPLOME  VALUES ('Maitrise Econometrie');
INSERT INTO CANDIDATURE.DIPLOME  VALUES ('Maitrise Informatique appliquée');
INSERT INTO CANDIDATURE.DIPLOME  VALUES ('DEA Economie Ressources Humaines');
INSERT INTO CANDIDATURE.DIPLOME  VALUES ('DESS Techniques Décisions');


-- Question 10

CREATE TABLE CANDIDATURE.CANDIDAT_LANGUE
 